name: Build and deploy Node.js app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'radadigital-mvp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXX }}
          package: .
          # Esta línea le dice a Azure que no se complique y que él mismo compile el código
          startup-command: 'npm install && npm run build'
